#include <stdio.h>
#include <stdlib.h>

void lecture1();
void lecture2();
void lecture3();
void lecture4();
void lecture4_2();
void lecture5();
void lecture6();
void lecture7();
void lecture8();
void lecture9();
void lecture10();
void lecture11();
void lecture12();
/// <summary>
/// 반복문 예제 문제
/// </summary>
void lecture12_2();
void lecture12_3();
void lecture13();
void lecture13_2();
void lecture14();
void lecture15();
void lecture16();
void lecture17();
void lecture18();
void lecture19();
void lecture20();
void lecture21();
void lecture22();
void lecture23();
void lecture24();
void lecture25();
void lecture26();
void lecture27();